[package]
name = "tetris-learning-environment"
version = "0.1.0"
authors = ["Atlas <achille@heraud.xyz>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
rand = "0.5.5"
agb-core = {git = "https://github.com/aHeraud/agb", rev="0bf1fbb21febd64ba3d7efe42b19260ea8ce0c25" }
